### ISSUE TITLE
Data Type Error

### ISSUE THREAD

**Issue by kaungminhtet1999** [Jsane001/G6-DevOps#62]
**Describe the bug**
Data type error.

**To Reproduce**
1. When using integer data type, data size cannot be enough to store data. Therefore, the output data are incorrect.

**Expected behavior**
If the data type can store, the output result can be shown correctly.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Windows 10 (IntelliJ software)
 - Version 0.1.Alpha.5

**Additional context**
None.

**Comment by NyeinChanSoe2** [comment]
Finished
