### ISSUE TITLE
Wrong variable name in report table

### ISSUE THREAD

**Issue by 40478648** [Jsane001/G6-DevOps#63]
**Describe the bug**
Wrong variable name in report table

**To Reproduce**
1. Function cannot applied that variable name

**Expected behavior**
A clear reports table will appear in reports file

**Screenshots**
None.

**Desktop (please complete the following information):**
 - Version 0.1.Alpha.5

**Additional context**
None.

**Comment by NyeinChanSoe2** [comment]
Finished

**Comment by 40478648** [comment]
Check the variable name in print function. Duplication and missing may occur in this issuse.
