### ISSUE TITLE
Wrong Design Format Error

### ISSUE THREAD

**Issue by 40478648** [Jsane001/G6-DevOps#64]
**Describe the bug**
A wrong design format error for report errors

**To Reproduce**
1. The output data are not include in report table.

**Expected behavior**
A clear report data will show with table.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - Version 0.1.Alpha.5
 - OS: Windows 10 (IntelliJ software)

**Additional context**
None.

**Comment by NyeinChanSoe2** [comment]
Finished

**Comment by 40478648** [comment]
Compare two design pattern to slove that issuse. The copy process is also very important in this issuse.
